source 'https://rubygems.org'

gem 'jekyll'
gem 'coderay'
gem 'sass', '3.4.5'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'jekyll-sitemap'
gem 'rouge'
gem 'gsl', :git => 'git://github.com/siefca/rb-gsl'
gem 'classifier-reborn', :git => 'git://github.com/jekyll/classifier-reborn.git'
gem 'narray'
gem 'rack-jekyll'
gem 'fast-stemmer'
gem 's3_website'
gem 'mercenary'